[package]
name = "unwinder"
version = "0.1.0"
edition = "2021"

[dependencies]
gimli = "0.26"
memmap = "0.7"
nix = "0.23"
libc = "0.2"
object = "0.28"
findshlibs = "0.10"
thiserror = "1.0"
addr2line = "0.17"
smallvec = "1"
rustc-demangle = "0.1.21"
locate-dwarf = "0.1.0"
